syntax = "proto3";

package profile.data;

service ProfileData {
  rpc getFollowers(getFollowersRequest) returns (getFollowersResponse);
  rpc getFollowing(getFollowingRequest) returns (getFollowingResponse);
  rpc getProfile(getProfileRequest) returns (getProfileResponse);
}

message getFollowersRequest {
  string profileId = 1;
}

message getFollowersResponse {
  int32 count = 1;
  repeated string followers = 2;
}

message getFollowingRequest {
  string profileId = 1;
}

message getFollowingResponse {
  int32 count = 1;
  repeated string following = 2;
}

message getProfileRequest {
  string profileId = 1;
}

message getProfileResponse {
  string username = 1;
  string avatarId = 2;
  string firstName = 3;
  string lastName = 4;
}
