apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    uid: redis
    access: proxy
    url: redis://redis:6379
    isDefault: false
    editable: false
    secureJsonData:
      password: ${REDIS_PASSWORD}
