filebeat.inputs:
  - type: log
    paths:
      - /logs/*.log
    scan_frequency: 5s

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  index: "breezy-logs-%{+yyyy.MM.dd}"

setup.template.name: "breezy-logs"
setup.template.pattern: "breezy-logs-*"
setup.ilm.enabled: false

logging.level: debug
logging.to_files: false
logging.to_stderr: true
