import { ROLES, type Role } from "./roles"
import { PERMISSIONS, type Permission } from "./permissions"

export const VISITOR_PERMISSIONS: Permission[] = [PERMISSIONS.ACCOUNT_CREATE]

const USER_PERMISSIONS: Permission[] = [PERMISSIONS.USER_READ, PERMISSIONS.REPORT_CREATE]

const MODERATOR_PERMISSIONS: Permission[] = [
  ...USER_PERMISSIONS,
  PERMISSIONS.REPORT_RESOLVE,
  PERMISSIONS.USER_SUSPEND,
]

const ADMIN_PERMISSIONS: Permission[] = [
  ...MODERATOR_PERMISSIONS,
  PERMISSIONS.USER_BAN,
  PERMISSIONS.USER_CREATE,
]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.USER]: USER_PERMISSIONS,
  [ROLES.MODERATOR]: MODERATOR_PERMISSIONS,
  [ROLES.ADMIN]: ADMIN_PERMISSIONS,
}
